replicaCount: 1

image:
  repository: mendhak/http-https-echo
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: 'latest'

nameOverride: ''
fullnameOverride: 'fullnameOverride'

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  className: 'nginx'
  annotations:
    {}
  hosts:
    - host: 'host'
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []